name: Convert Data and Create cn.conf

on:
  push:
    branches:
      - main

jobs:
  convert_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get Raw Data
        run: |
          curl -o raw_data.txt https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/china-list.txt

      - name: Convert Data
        run: |
          sed 's/^/server=\/&\/119.29.29.29/' raw_data.txt > cn.conf

      - name: Store cn.conf in Repository
        run: |
          mkdir converted_data_folder
          cp cn.conf converted_data_folder/

      - name: Commit Changes
        run: |
          git config --local user.email "37972397+angwz@users.noreply.github.com"
          git config --local user.name "angwz"
          git clone https://github.com/angwz/dnsmasq-conf.git temp-repo
          cp -r converted_data_folder/* temp-repo/
          cd temp-repo
          git add .
          git commit -m "Add cn.conf file"
          git push origin main
