name: Generate cn.conf file

# 触发工作流的事件，这里设置为每次push到main分支时
on:
  push:
    branches: [ main ]

# 定义一个或多个工作流任务
jobs:
  # 任务的名称，可以自定义
  generate-file:
    # 任务运行的环境，这里设置为ubuntu最新版
    runs-on: ubuntu-latest
    # 任务的步骤
    steps:
      # 第一步，使用actions/checkout@v4来检出仓库代码
      - name: Check out repository code
        uses: actions/checkout@v4
        
      - name: Get Raw Data
        run: |
          wget https://raw.githubusercontent.com/username/other-repo/main/data.txt -O raw_data.txt  # Replace URL with the raw text file's address

      - name: Convert Data
        run: |
          sed 's/^/server=\/&\/119.29.29.29/' raw_data.txt > cn.conf  # Modify text content and generate cn.conf file
      # 第三步，使用actions/upload-artifact@v2来上传生成的cn.conf文件
      - name: Upload cn.conf file
        uses: actions/upload-artifact@v2
        with:
          name: cn.conf
          path: cn.conf
      # 第四步，使用ad-m/github-push-action@v0来推送cn.conf文件到仓库
      - name: Push cn.conf file to repository
        uses: ad-m/github-push-action@v0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
