name: Convert Data and Create cn.conf

on:
  schedule:
    - cron: '0 16 * * 0'  # 北京时间每周一的00:00，UTC时间为每周日的16:00
    
  workflow_dispatch:  # 添加此行以允许手动触发

jobs:
  convert_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Git config
        run: |
          git config --global user.email "37972397+angwz@users.noreply.github.com"
          git config --global user.name "angwz"

      - name: Get Raw Data
        run: |
          curl -o raw_data.txt https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/china-list.txt

      - name: Convert Data
        run: |
          sed 's/^\(.*\)$/server=\/\1\/119.29.29.29/' raw_data.txt > cn.conf

      - name: Commit Changes
        run: |
          mkdir converted_data_folder
          cp cn.conf converted_data_folder/
          cd converted_data_folder
          git init  # 初始化一个新的 Git 仓库
          git add .
          git commit -m "Add cn.conf file"
          git remote add origin https://${{ secrets.DNSMASQ_CONF_TOKEN }}@github.com/angwz/dnsmasq-conf.git
          git push -f origin main  # 强制覆盖远程仓库中的文件
