name: Convert Data and Create cn.conf

on:
  schedule:
    - cron: '0 16 * * 0'  # 北京时间每周一的00:00，UTC时间为每周日的16:00
    
  workflow_dispatch:  # 添加此行以允许手动触发

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get Raw Data
        run: |
          curl -o raw_data.txt https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/china-list.txt

      - name: Convert Data
        run: |
          sed 's/^\(.*\)$/server=\/\1\/119.29.29.29/' raw_data.txt > cn.conf

      - name: Store cn.conf in Repository
        run: |
          mkdir converted_data_folder
          cp cn.conf converted_data_folder/

      - name: Commit Changes
        run: |
          git config --local user.email "37972397+angwz@users.noreply.github.com"
          git config --local user.name "github-action[bot]"
          
          git fetch
          git checkout release
  
          git checkout --orphan release-orphan
          git rm -rf .
  
          cp -rf converted_data_folder/cn.conf ./
  
          git add cn.conf
          git commit -am "Updated at $(date)"
  
          git branch -D release
          git branch -m release

      - name: GitHub Push
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.DNSMASQ_CONF_TOKEN }}
          branch: release
          force: true
